authors:
  fbetteo:
    name: Franco Betteo
    description: Creator
    avatar: https://media.licdn.com/dms/image/v2/D4D03AQGGiT9NDiLy7Q/profile-displayphoto-shrink_200_200/profile-displayphoto-shrink_200_200/0/1681511830071?e=1738195200&v=beta&t=Nd1WNLQTxHfCe7dT9BBaQYgaYtEHFCOPpntpImC4Lz8
    url: https://x.com/intent/follow?screen_name=franbetteo